language: java

jdk:
  # Tests On Travis CI fail with Java7 due to this exception...
  #   java.security.NoSuchProviderException: no such provider: SunEC
  # - openjdk7
  # - oraclejdk7
  - openjdk8
  - oraclejdk8

addons:
  hostname: fluency-builder

install:
  - ./gradlew assemble -x signArchives -x uploadArchives

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

script:
  - ./gradlew check --debug --stacktrace --info

after_success:
  - ./gradlew jacocoTestReport coveralls
